name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t vetri20/flask-app:latest .
          docker push vetri20/flask-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure credentials
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Azure CLI
        uses: azure/CLI@v1

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group myResourceGroup --name MyAKSCluster --overwrite-existing

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.24.0

      - name: Deploy Flask app to AKS
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml

      - name: Deploy Linkerd configurations for Flask app
        run: |
          kubectl apply -f kubernetes/linkerd-virtualservice.yaml

      - name: Deploy Nagios to AKS
        run: |
          kubectl apply -f kubernetes/nagios-deployment.yaml
          kubectl apply -f kubernetes/nagios-service.yaml

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/flask-app
          kubectl rollout status deployment/nagios
